version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    restart: always
    ports:
      - 9870:9870  # Hadoop NameNode UI
      - 9000:9000  # HDFS Port
    environment:
      - CLUSTER_NAME=farmbti-cluster
    networks:
      - farmbti
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    restart: always
    environment:
      - SERVICE_PRECONDITION=hadoop-namenode:9000
    networks:
      - farmbti
    depends_on:
      - namenode
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-resourcemanager
    restart: always
    ports:
      - 8088:8088  # YARN UI
    networks:
      - farmbti
    depends_on:
      - namenode

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-nodemanager
    restart: always
    networks:
      - farmbti
    depends_on:
      - resourcemanager

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-historyserver
    restart: always
    ports:
      - 8188:8188  # JobHistory UI
    networks:
      - farmbti
    depends_on:
      - namenode
      - resourcemanager
    volumes:
      - historyserver_data:/hadoop/yarn/timeline

networks:
  farmbti:
    external: true  # 기존 네트워크 활용

volumes:
  hadoop_namenode:
  hadoop_datanode:
  historyserver_data:
