version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: farmbti-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - farmbti

networks:
  farmbti:
    external: true