version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: farmbti-nginx
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /var/jenkins_home/app/frontend/farmbti/dist:/usr/share/nginx/html
    networks:
      - farmbti

networks:
  farmbti:
    external: true
