version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: farmbti-nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../../frontend/farmbti/dist:/usr/share/nginx/html
    networks:
      - farmbti

networks:
  farmbti:
    external: true
