version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farmbti-frontend
    ports:
      - "3000:80"
    networks:
      - farmbti

networks:
  farmbti:
    external: true
