pipeline {
    agent any

    tools {
        nodejs 'node18'
    }

    environment {
        GIT_CREDENTIALS_ID = 'gitlab-credentials'
        FRONT_PROJECT_DIR = "frontend/farmbti"
        DIST_DIR = "frontend/farmbti/dist"
        NGINX_DIR = "backend/infra/nginx"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: 'front']],
                    userRemoteConfigs: [[
                        url: 'https://lab.ssafy.com/s12-bigdata-dist-sub1/S12P21D209.git',
                        credentialsId: "${GIT_CREDENTIALS_ID}"
                    ]]
                ])
                sh 'echo "✅ 코드 체크아웃 완료"'
            }
        }

        stage('Build Frontend') {
            steps {
                dir("frontend/farmbti") {
                    sh '''
                    echo "✅ 프론트엔드 빌드 시작"
                    rm -rf node_modules dist
                    npm install --legacy-peer-deps
                    npm run build
                    echo "✅ 프론트엔드 빌드 완료"
                    '''
                }
            }
        }

        stage('Copy dist to Nginx target') {
            steps {
                sh '''
                echo "✅ 프론트 dist 디렉토리 복사 시작"
                rm -rf /home/ubuntu/jenkins-data/workspace/farmbti-be/infra/nginx/dist
                cp -r /home/ubuntu/jenkins-data/workspace/farmbti-fe/frontend/farmbti/dist /home/ubuntu/jenkins-data/workspace/farmbti-be/infra/nginx/
                echo "✅ 복사 완료"
                '''
            }
        }
    }
}
