pipeline {
    agent any

    tools {
        nodejs 'node18'
    }

    environment {
        GIT_CREDENTIALS_ID = 'gitlab-credentials'
        FRONT_PROJECT_DIR = "frontend/farmbti"
        DIST_DIR = "frontend/farmbti/dist"
        NGINX_DIR = "backend/infra/nginx"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: 'front']],
                    userRemoteConfigs: [[
                        url: 'https://lab.ssafy.com/s12-bigdata-dist-sub1/S12P21D209.git',
                        credentialsId: "${GIT_CREDENTIALS_ID}"
                    ]]
                ])
                sh 'echo "✅ 코드 체크아웃 완료"'
            }
        }

        stage('Build Frontend') {
            steps {
                dir("frontend/farmbti") {
                    sh '''
                    echo "✅ 프론트엔드 빌드 시작"
                    rm -rf node_modules dist
                    npm install --legacy-peer-deps
                    npm run build
                    echo "✅ 프론트엔드 빌드 완료"
                    '''
                }
            }
        }

        stage('Copy dist to Nginx') {
            steps {
                script {
                    sh '''
                    echo "[INFO] 기존 dist 삭제 중..."
                    rm -rf /home/ubuntu/nginx/dist

                    echo "[INFO] 새로운 dist 복사 중..."
                    cp -r frontend/farmbti/dist /home/ubuntu/nginx/dist

                    echo "[INFO] dist 복사 완료 ✅"
                    '''
                }
            }
        }
    }
}
