spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
server:
  port: 18081
jwt:
  secret-key: ${JWT_SECRET}
  expiration-time: 3600000
  token-prefix: "Bearer "
  header-string: "Authorization"
  issuer: "your-app-name"
  refresh-expiration-time: 86400000
logging:
  level:
    root: INFO
    com.backend.farmbti: DEBUG
    com.backend.farmbti.security.filter: DEBUG
zeppelin:
  base-url: "http://3.39.65.150:18888"