version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: farmbti_db
      POSTGRES_USER: ssafy
      POSTGRES_PASSWORD: ssafy209!@
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - farmbti

  backend:
    container_name: farmbti-backend
    build: .
    image: nageum/farmbti_backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - KAKAO_API_KEY=a24122d363b6f9d33ce3566b2f018f124
      - client-id=1TgtpJ9xAyA_fHiy9pRI
      - client-secret=ijnEAaSVcU
      - url=https://openapi.naver.com/v1/search/news.json
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    networks:
      - farmbti

networks:
  farmbti:
    external: true

volumes:
  postgres-data: