version: '3.8'

services:
  backend:
    container_name: farmbti-backend
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    networks:
      - farmbti

networks:
  farmbti:
    external: true