version: '3.8'

services:
  backend:
    container_name: farmbti-backend
    build: .
    expose:
      - "8081"
    env_file:
      - .env
    networks:
      - farmbti

networks:
  farmbti:
    external: true