version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/farmbti
      dockerfile: Dockerfile
    container_name: farmbti-frontend
    restart: always
    networks:
      - farmbti

  nginx:
    image: nginx:latest
    container_name: farmbti-nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/farmbti/dist:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - farmbti

networks:
  farmbti:
    external: true