version: '3.8'

services:
  backend:
    container_name: farmbti-backend
    build: .
    image: nageum/farmbti_backend
    ports:
      - "8081:8081"
    env_file:
      - .env
    #environment:
    #  - DB_URL=${DB_URL}
    #  - DB_USERNAME=${DB_USERNAME}
    #  - DB_PASSWORD=${DB_PASSWORD}
    #  - REDIS_HOST=${REDIS_HOST}
    #  - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    networks:
      - farmbti

networks:
  farmbti:
    external: true