version: '3.8'

services:
  backend:
    container_name: farmbti-backend
    build: .
    image: ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    networks:
      - farmbti

networks:
  farmbti:
    external: true