version: '3.8'

services:
  backend:
    container_name: farmbti-backend
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - farmbti

networks:
  farmbti:
    external: true
