version: '3.8'

services:
  backend:
    container_name: farmbti-backend
    build: .
    image: nageum/farmbti_backend
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - farmbti

  postgres:
    container_name: farmbti-db
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmbti

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  farmbti:
    external: true

volumes:
  postgres_data:
  redis_data: