version: "2.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ssafy
      POSTGRES_PASSWORD: ssafy209!@ 
      POSTGRES_DB: farmbti_db 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmbti

  redis:
    image: redis 
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - farmbti

volumes:
  postgres_data:

networks:
  farmbti:
    name: farmbti
    driver: bridge

