version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmbti

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - farmbti

volumes:
  postgres_data:
  redis_data:

networks:
  farmbti:
    name: farmbti
    driver: bridge
